### ISSUE TITLE
CSS and Javascript files attached to a module

### ISSUE THREAD

**Issue by kasimus** [coreframework/Core-Framework#1]
There are two related issues actually:
1. That would be great to have a way to attach CSS and Javascript files to a particular module. Moreover, note that if I have two modules on the page that use the same CSS or Javascript (more common case) you should handle this and download this script or css file once. 
1. When you load you widget using AJAX it doesn't load css and script files.

**Comment by coreframework** [comment]
Added in version 3.0.8
