### ISSUE TITLE
There's no support for transactions in the data services

### ISSUE THREAD

**Issue by karpenkov** [coreframework/Core-Framework#10]
Hi,

It seems like the framework doesn't have built-in support for DB transactions. Please take a look at the Castle Transaction Services and Auto Tx Facility (http://groups.google.com/group/castle-project-users/browse_thread/thread/737efe78fe0f7a9d) for this and see if it can be useful here. Thank you.

**Comment by coreframework** [comment]
Implemented in version 3.0.10.
