### ISSUE TITLE
Use Linq instead of ICriteria in the data services implementations

### ISSUE THREAD

**Issue by karpenkov** [coreframework/Core-Framework#11]
Hi,

I would rather advise on using Linq instead of ICriteria in the data services implementations for purposes making the code more easy to refactor and understand. Please make sure to upgrade to the newest NHibernate for better Linq support. Thank you.

**Comment by coreframework** [comment]
NHibernate version was upgrade to v.3.1.0. New features development uses Linq. Replacement of ICriteria takes place as refactoring of particular block of code is going.
