### ISSUE TITLE
Database Script?

### ISSUE THREAD

**Issue by aap21** [coreframework/Core-Framework#16]
I can not locate a database script. I followed the instructions, but does the framework automatically create the tables in the database? I got an nHibernate error 

I found a sql script in WebGallery directory and ran it against CoreFramework db but doesnt seem complete
System.Data.SqlClient.SqlException: Invalid object name 'PluginLocales'.

**Comment by coreframework** [comment]
There are some issues with automatically database creation. As a hotfix sql script "corev10.sql" was added to the root at "master" branch.

**Comment by aap21** [comment]
Great

I will try it

thanks
