### ISSUE TITLE
There is an issue with localization

### ISSUE THREAD

**Issue by kasimus** [coreframework/Core-Framework#3]
Hi,

There is an intermittent issue with localization. Here is what I sometimes get (highlighted):
![Issueo](http://web.itransition.com/UserFiles/core-localization-issue.jpg)

After rebooting the application everything works OK but then it appears again.

P.S. Please also note how close icon is misaligned in Chrome 13.0.78...

Thanks

**Comment by coreframework** [comment]
Couldn't reproduce localization issue in version 3.0.7. Slicing bug in Chrome fixed.
