### ISSUE TITLE
Issue with widgets drag'n'drop feature

### ISSUE THREAD

**Issue by kasimus** [coreframework/Core-Framework#5]
Hi,

There is an issue with drag n drop function. Here are two screenshots:
1. The original widgets layout:
![](http://web.itransition.com/UserFiles/core-widgets-dragndrop-issue1.JPG)
2. Here is an issue - see how the bottom widget changed its layout while I'm dragging the top one.
![](http://web.itransition.com/UserFiles/core-widgets-dragndrop-issue2.JPG)

HTML code snippet from the bottom widget:

<pre><code>
&lt;div style=&quot;padding: 10px 5px; border: 1px solid #72a1db; margin: 5px 0px; width: 440px; float: left; margin-right: 5px&quot;&gt;
    &lt;div style=&quot;width: 65px; display: inline; float: left; padding: 3px 0px&quot;&gt;
        &lt;label for=&quot;Width&quot;&gt;Width&lt;/label&gt;
    &lt;/div&gt;
    &lt;div style=&quot;display: inline; float: left;&quot;&gt;
       ...
    &lt;/div&gt;
    &lt;div style=&quot;width: 65px; display: inline; float: left; padding: 3px 0px 3px 5px&quot;&gt;
        &lt;label for=&quot;Height&quot;&gt;Height&lt;/label&gt;
    &lt;/div&gt;
    &lt;div style=&quot;display: inline&quot;&gt;
        ...  
    &lt;/div&gt;
&lt;/div&gt;
&lt;div style=&quot;padding: 10px 5px; border: 1px solid #72a1db; margin: 5px 0px; width: 440px; float: left; margin-right: 5px&quot;&gt;
    &lt;div style=&quot;width: 65px; display: inline; float: left; padding: 3px 0px&quot;&gt;
        &lt;label for=&quot;ChartColor&quot;&gt;Chart color&lt;/label&gt;
    &lt;/div&gt;
    &lt;div style=&quot;display: inline; float: left;&quot;&gt;
        ...    
    &lt;/div&gt;
    &lt;div style=&quot;width: 65px; display: inline; float: left; padding: 3px 0px 3px 5px&quot;&gt;
        &lt;label for=&quot;ChartType&quot;&gt;Chart type&lt;/label&gt;
    &lt;/div&gt;
    &lt;div style=&quot;display: inline&quot;&gt;
        ...
    &lt;/div&gt;
&lt;/div&gt;
</code></pre>

**Comment by coreframework** [comment]
Resolved in version 3.0.10.
