### ISSUE TITLE
Issue with widgets drag & drop feature after saving widget settings

### ISSUE THREAD

**Issue by lisovskym** [coreframework/Core-Framework#6]
Hi,
There is an issue with drag n drop functionality after saving widget settings
1. The original widgets layout:
   ![First step](http://web.itransition.com/RWCWebToolDev/content/images/github/first%20step.jpg)
2. Then I edit settings for some widgets, then save it.
   ![Second step](http://web.itransition.com/RWCWebToolDev/content/images/github/second%20step.jpg)
3. Then  I try to move some widgets, after that I get following result:
   ![Third step](http://web.itransition.com/RWCWebToolDev/content/images/github/third%20step.jpg)

**Comment by coreframework** [comment]
Fixed in version 3.0.7
