### ISSUE TITLE
Upgrade 3rd party libraries to their latest versions

### ISSUE THREAD

**Issue by karpenkov** [coreframework/Core-Framework#9]
Hi,

It seems like the framework uses some outdated libraries, e.g. NHibernate, Castle etc. Do you plan to keep them up to date?

**Comment by coreframework** [comment]
Implemented in version 3.0.10.

List of main changes:
NHibernate 2.1.2 -> 3.1.0;
Castle.Core 1.2.0 -> 3.0.0;
Castle.Windsor 2.1.0 -> 3.0.0;
Castle.Facilities.Logging 2.1.0 -> 3.0.0;
Castle.Services.Logging.log4netIntegration 1.2.0 -> 3.0.0;
Castle.Services.Transaction 2.0.0 -> 2.5.0;
log4net 1.2.10 -> 1.2.11;
NUnit 2.5.5 -> 2.5.10;
ECM7.Migrator 2.5.0 -> 2.6.0.
